baseURL = "https://ttult.github.io/"
languageCode = "ja"
title = "Ultimate ROOM"
theme = "PaperMod"
defaultContentLanguage = "ja"
hasCJKLanguage = true
enableRobotsTXT = true

[pagination]
  pagerSize = 20

# 出力形式（HTML + JSON APIなど）
[outputs]
home = ["HTML", "JSON"]

[params]
  siteDescription = "R18系電子データの最新情報を自動収集・更新するポータルサイト。ジャンルやタグで探しやすく、作者情報や作品リンクもすぐ確認可能。海外展開も視野に。"
  author = "Ultimate ROOM"
  keywords = ["R18", "同人", "電子書籍", "CG集", "ゲーム", "最新情報"]

  # taxonomies系(タグなど)
  showToc = true
  showTaxonomies = true
  showTags = true
  showCategories = true

  # 記事カード表示設定
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true

  mainSections = ["posts"] # posts ディレクトリをメインに

  [params.list]
    showDate = true
    showReadingTime = true
    showSummary = true
    showTags = true

[markup.goldmark.renderer]
unsafe = true

[taxonomies]
  category = "categories"
  tag = "tags"

[menu]
  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 10

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 20